version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Pull Submodules
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Test debian:latest + GCC
          command: make test-docker-latest-debian-gcc
